notifications:
  email: false

language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"

go_import_path: ./github.com/loeffel-io/go-aes

before_script:
  - make install
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 19d29a41-e4d3-41e0-9ec6-6ec0a5fd2378